CREATE TABLE IF NOT EXISTS settings (
	username STRING,
	email STRING
);

CREATE TABLE IF NOT EXISTS items (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	slot STRING NOT NULL,
	name STRING NOT NULL,
	brand STRING,
	type STRING NOT NULL,
	created DATETIME NOT NULL,
	purchased DATETIME,
	notes STRING,
	material STRING,
	pattern STRING,
	size STRING,
	sleevelength STRING,
	price DECIMAL,
	formality STRING,
	fit STRING,
	wear STRING,
	warmth STRING,
	color1 STRING NOT NULL,
	color2 STRING,
	color3 STRING
);

CREATE TABLE IF NOT EXISTS outfits (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name STRING NOT NULL,
	type STRING NOT NULL,
	created DATETIME NOT NULL,
	notes STRING
);

CREATE TABLE IF NOT EXISTS slots (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	outfit INT,
	item INT,
	FOREIGN KEY(outfit) REFERENCES outfits(id),
	FOREIGN KEY(item) REFERENCES items(id)
);